### ISSUE TITLE
Fallback monospace fonts?

### ISSUE THREAD

**Issue by agentydragon** [nmartin84/logseq-solarized#2]
I'm on Ubuntu and don't have the SF Mono font, and inline code got rendered as serif font for me. I just added this to my `custom.css`:

```css
/* https://github.com/logseq/logseq/blob/53531862cb15809c2211f598286acb58a63cbc52/resources/css/common.css#L1069 */
:not(pre)>code {
  font-family: 'Ubuntu Mono', monospace;
}

/* https://github.com/logseq/logseq/blob/56de7fbd4073f6e7d8e34258af3fc773377a91a7/src/main/frontend/extensions/code.css#L28 */
.extensions__code-calc-output-line > span,
/* https://github.com/logseq/logseq/blob/56de7fbd4073f6e7d8e34258af3fc773377a91a7/src/main/frontend/extensions/code.css#L38 */
.CodeMirror {
  font-family: 'Ubuntu Mono', monospace;
}
```

Consider adding `monospace` as generic fallback. Or, I think it might actually be a good idea to not set fonts in this scheme at all. That way it would do just the colors stuff, and not also change fonts.
